# Generated by Django 5.0.6 on 2024-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cure',
                'verbose_name_plural': 'cures',
                'db_table': 'cures',
            },
        ),
        migrations.CreateModel(
            name='CureDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'cure_disease',
                'verbose_name_plural': 'cures_diseases',
                'db_table': 'cures_diseases',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'diagnostic_disease',
                'verbose_name_plural': 'diagnostics_diseases',
                'db_table': 'diagnostics_diseases',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'disease',
                'verbose_name_plural': 'diseases',
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plant',
                'db_table': 'plants',
            },
        ),
    ]
