# Generated by Django 5.0.6 on 2024-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curedisease',
            name='cure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticdisease',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.disease'),
        ),
        migrations.AddField(
            model_name='curedisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.disease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='plant.plant'),
        ),
    ]
