# Generated by Django 5.0.6 on 2024-05-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curedisease',
            name='cure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.cure'),
        ),
    ]
