# Generated by Django 5.0.6 on 2024-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_curedisease_cure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticDisease',
        ),
    ]
