# Generated by Django 5.0.6 on 2024-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('plant_image', models.CharField(max_length=255)),
                ('is_infected', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='plant.plant')),
            ],
            options={
                'verbose_name': 'diagnostic',
                'verbose_name_plural': 'diagnostics',
                'db_table': 'diagnostics',
            },
        ),
    ]
