# Generated by Django 5.0.6 on 2024-05-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_delete_diagnosticdisease'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='plant.disease'),
            preserve_default=False,
        ),
    ]
