# Generated by Django 5.0.6 on 2024-05-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_delete_diagnosticdisease'),
        ('user', '0002_diagnostic_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='plant.disease'),
        ),
    ]
