# Generated by Django 5.0.6 on 2024-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_diagnostic_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
